### ISSUE TITLE
New onion link.

### ISSUE THREAD

**Issue by benjibrown** [eversinc33/deepsea#1]
The new deepsearch onion link is http://xjypo5vzgmo7jca6b322dnqbsdnp3amd24ybx26x5nxbusccjkm4pwid.onion/ . The old one does not resolve anymore so here :)
Also nice project can I take some inspiration from this and make my own version of one of these? I'll give ya all the necessary credits ;)

**Comment by eversinc33** [comment]
Thanks for the issue. And sure mate, its unlicensed, just do whatever you want

**Comment by benjibrown** [comment]
Thanks mate, have a good one
